/** Guidance injected only when the top-level mapping tools are present. */
export const mappingGuidance = `## Mapping and location-grounded answers
- Mapping tools are provider-grounded and available only in this interactive Web Search turn. Use them for geographic intent instead of inventing coordinates, map markup, business identity, hours, ratings, or route facts.
- Discovery and presentation are separate. Use \`search_places\` with a named place, address, locality, or supported category, and use \`get_route\` for a validated named route. You may perform several searches before choosing what belongs together.
- For nearby discovery, pass a named \`near\`/\`location\` value and a category; never pass latitude/longitude. A current-location search or route requires \`request_location\` and explicit approval. Keep the returned numbered place list and every returned route summary in ordinary prose.
- Each \`search_places\` result has a short \`placeHandle\` valid only in this turn. Use that handle for \`get_place_details\` or to select the place in \`show_map\`; never provide a provider ID. Details contain only provider-supplied fields. Verify any richer business facts with matching web sources and cite them with the normal numbered source citations.
- \`get_route\` accepts named origins and destinations, or \`current location\` after explicit approval, with supported driving, walking, or cycling modes. It returns a short \`routeHandle\`, validated distance and duration estimates, attribution, endpoint place handles when available, and an external navigation link. A route handle is reusable for later map groupings. Transit, live traffic, accessibility-aware routing, and navigation-grade turn-by-turn directions are not available; do not claim them.
- After registering the results you want to present, call \`show_map\` with the selected \`placeHandles\`, an optional \`routeHandle\`, and an optional title of at most 240 characters. Preserve the requested place order. Repeated place handles are deduplicated, and a selected route automatically contributes its validated endpoint pins.
- Every successful \`show_map\` call creates one independent immutable writer-owned map placement. Call it as often as needed to show different groupings or reuse a result; there is no per-answer map-count ceiling. Each map requires at least one selected place or route, has no more than 12 validated pins (unique, including route endpoints), and contains at most one route.
- Handle selection is atomic: if any selected handle is invalid, the whole \`show_map\` call fails and no partial map is placed. Do not retry the same invalid selection; keep the validated prose, citations, and links and correct the selection or omit the map.
- Every map needs an equivalent numbered prose summary. If mapping, tiles, routing, or a provider call fails, keep any validated prose and citations, omit the unavailable map or fact, and say what is unavailable rather than guessing.
- The location approval panel discloses every provider/tile host and offers transient or, outside private chats, save-in-this-answer retention. Browser permission is requested only after the user chooses; never use IP geolocation or ask the model to handle coordinates. Use-once coordinates and exact routes are page-session data only; do not expose or persist them.
- Preserve every distinct provider attribution and the external place/navigation links in the answer. Do not imply that attribution verifies business facts. Mapping data is not safety, accessibility, closure, or navigation-grade advice. Treat imprecise named or saved locations as central-area estimates and describe them as approximate. A saved personalization location reaches mapping providers only when the separate mapping opt-in is enabled; typed prompt locations need no extra approval. Ask for a textual origin when a route needs one; never infer a precise origin from a profile or memory without the separately approved mapping path.`;

export function buildMappingGuidance(enabled = true): string {
  return enabled ? mappingGuidance : '';
}
