/** Guidance injected only when the top-level mapping tools are present. */
export const mappingGuidance = `## Mapping and location-grounded answers
- Mapping tools are provider-grounded and available only in this interactive Web Search turn. Use them for geographic intent instead of inventing coordinates, map markup, business identity, hours, ratings, or route facts.
- Use \`search_places\` with a named place, address, locality, or supported category. For nearby discovery, pass a named \`near\`/\`location\` value and a category; never pass latitude/longitude. Keep the returned numbered place list in ordinary prose. A result's short \`placeHandle\` is the only valid input to \`get_place_details\`.
- Use \`get_place_details\` only with a placeHandle returned in this turn. It returns only fields the provider supplied. For additional business enrichment, verify that web sources describe the same provider identity and address before combining facts. Cite hours, ratings, recommendations, and richer business facts with the normal numbered source citations; provider or tile attribution is not evidence for those claims.
- Use \`request_location\` before a \`near\`/\`location\` search around the user or a route whose origin is \`current location\`. The approval panel discloses every provider/tile host and offers transient or, outside private chats, save-in-this-answer retention. Browser permission is requested only after the user chooses; never use IP geolocation or ask the model to handle coordinates.
- Use \`get_route\` only for named origins and destinations, or \`current location\` after explicit approval, and the supported driving, walking, or cycling modes. It returns a short \`mapHandle\`/\`routeHandle\`, validated distance and duration estimates, attribution, and an external navigation link. Transit, live traffic, accessibility-aware routing, and navigation-grade turn-by-turn directions are not available; do not claim them.
- Call \`show_map\` at most once, after the provider results you want to show are registered, using only a returned mapHandle or routeHandle. Never pass raw coordinates, private IDs, guessed handles, legacy tags, or model-authored \`yaawc:\` fences. The writer owns map placement.
- Every map needs an equivalent numbered prose summary. A map may contain no more than 12 validated pins and one route. If mapping, tiles, routing, or a provider call fails, keep any validated prose and citations, omit the unavailable map/fact, and say what is unavailable rather than guessing.
- Mapping data is not safety, accessibility, closure, or navigation-grade advice; do not infer those claims from a distance or route estimate. Treat imprecise named or saved locations as central-area estimates and describe them as approximate. A saved personalization location reaches mapping providers only when the separate mapping opt-in is enabled; typed prompt locations need no extra approval. Ask for a textual origin when a route needs one; never infer a precise origin from a profile or memory without the separately approved mapping path.
- Preserve provider attribution and the external place/navigation links in the answer. Do not imply that attribution verifies business facts.`;

export function buildMappingGuidance(enabled = true): string {
  return enabled ? mappingGuidance : '';
}
