'use client';

import { useState } from 'react';

const STORAGE_KEY = 'codeExecutionWarningAccepted';

export function hasAcceptedWarning(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(STORAGE_KEY) === 'true';
}

export function acceptWarning(): void {
  localStorage.setItem(STORAGE_KEY, 'true');
}

type Props = {
  onAccept: () => void;
  onDecline: () => void;
};

export function CodeExecutionWarning({ onAccept, onDecline }: Props) {
  const [declining, setDeclining] = useState(false);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-overlay">
      <div className="bg-surface max-w-2xl max-h-[80vh] overflow-y-auto rounded-surface border border-surface-2 shadow-floating mx-4">
        <div className="bg-warning-soft border-b border-warning px-6 py-4">
          <h2 className="text-lg font-semibold text-fg flex items-center gap-2">
            ⚠ Code Execution — Risk Acknowledgment
          </h2>
        </div>
        <div className="px-6 py-4 space-y-4 text-sm text-fg/90">
          <div>
            <p className="font-medium mb-2">What this feature does:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                The AI assistant has generated code it wants to run on your
                machine.
              </li>
              <li>
                Code executes inside a Docker container with significant
                security restrictions.
              </li>
              <li>
                You will be shown each code snippet and asked to approve or deny
                it individually.
              </li>
            </ul>
          </div>

          <div>
            <p className="font-medium mb-2">What the sandboxed code CAN do:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                Run arbitrary JavaScript/Node.js code, including{' '}
                <code className="px-1 py-0.5 rounded-control bg-surface-2 font-mono text-xs">
                  require(&apos;child_process&apos;)
                </code>
              </li>
              <li>
                Read the container&apos;s filesystem (standard Node.js image
                contents)
              </li>
              <li>
                Write to{' '}
                <code className="px-1 py-0.5 rounded-control bg-surface-2 font-mono text-xs">
                  /tmp
                </code>{' '}
                (up to 64MB, non-persistent)
              </li>
              <li>
                Use up to 128MB of memory and 0.5 CPU for up to 30 seconds
              </li>
              <li>Spawn up to 32 processes inside the container</li>
            </ul>
          </div>

          <div>
            <p className="font-medium mb-2">
              What the sandboxed code CANNOT do:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Access the network (networking is fully disabled)</li>
              <li>
                Read or write your host filesystem (no volumes are mounted)
              </li>
              <li>
                Persist any data between executions (containers are destroyed
                after each run)
              </li>
              <li>Escalate privileges (all Linux capabilities are dropped)</li>
              <li>
                Modify the container&apos;s root filesystem (it is read-only)
              </li>
            </ul>
          </div>

          <div className="border border-warning bg-warning-soft rounded-control p-4">
            <p className="font-medium mb-2">Residual risks — read carefully:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong>Container escapes are possible.</strong> Docker
                sandboxing relies on Linux kernel namespaces and cgroups. Kernel
                vulnerabilities have historically allowed container escapes.
              </li>
              <li>
                <strong>The code is generated by an AI.</strong> The AI may
                produce code that behaves unexpectedly.
              </li>
              <li>
                <strong>Docker socket access is powerful.</strong> If your
                deployment mounts the Docker socket, the code execution feature
                has indirect access to a root-equivalent API on the host.
              </li>
              <li>
                <strong>You are responsible for your infrastructure.</strong>{' '}
                This feature is designed for self-hosted deployments where the
                operator understands and accepts these tradeoffs.
              </li>
            </ul>
          </div>

          <p className="text-fg/70 text-xs italic">
            If you do not understand the risks described above, do not enable
            code execution. Click &quot;Decline&quot; to deny this and all
            future code execution requests.
          </p>
        </div>

        <div className="flex justify-end gap-3 px-6 py-4 border-t border-surface-2">
          <button
            onClick={() => {
              setDeclining(true);
              onDecline();
            }}
            disabled={declining}
            className="px-4 py-2 text-sm rounded-control bg-danger-soft text-danger hover:bg-danger-soft border border-danger transition-colors disabled:opacity-50"
          >
            Decline
          </button>
          <button
            onClick={() => {
              acceptWarning();
              onAccept();
            }}
            className="px-4 py-2 text-sm rounded-control bg-success-soft text-success hover:bg-success-soft border border-success transition-colors"
          >
            I understand the risks — Enable code execution
          </button>
        </div>
      </div>
    </div>
  );
}
