'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/Button';
import Modal from '@/components/ui/Modal';

const STORAGE_KEY = 'codeExecutionWarningAccepted';

export function hasAcceptedWarning(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(STORAGE_KEY) === 'true';
}

export function acceptWarning(): void {
  localStorage.setItem(STORAGE_KEY, 'true');
}

type Props = {
  onAccept: () => void | Promise<void>;
  onDecline: () => void;
  mode?: 'manual' | 'auto-run';
  loading?: boolean;
  error?: string | null;
};

export function CodeExecutionWarning({
  onAccept,
  onDecline,
  mode = 'manual',
  loading = false,
  error,
}: Props) {
  const [declining, setDeclining] = useState(false);
  const autoRun = mode === 'auto-run';

  const decline = () => {
    setDeclining(true);
    onDecline();
  };

  return (
    <Modal
      open
      onClose={decline}
      bodyClassName="p-0"
      footer={
        <>
          <Button
            variant="dangerSoft"
            size="lg"
            onClick={decline}
            disabled={declining || loading}
          >
            {autoRun ? 'Cancel' : 'Decline'}
          </Button>
          <Button
            variant="successSoft"
            size="lg"
            onClick={() => {
              if (!autoRun) acceptWarning();
              void onAccept();
            }}
            loading={loading}
          >
            {autoRun
              ? 'I understand the risks — Enable auto-run'
              : 'I understand the risks — Enable code execution'}
          </Button>
        </>
      }
    >
      <div className="bg-warning-soft border-b border-warning px-6 py-4">
        <h2 className="text-lg font-semibold text-fg flex items-center gap-2">
          ⚠ {autoRun ? 'Auto-run Code' : 'Code Execution'} — Risk Acknowledgment
        </h2>
      </div>
      <div className="px-6 py-4 space-y-4 text-sm text-fg/90">
        <div>
          <p className="font-medium mb-2">What this feature does:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              The AI assistant has generated code it wants to run on your
              machine.
            </li>
            <li>
              Code executes inside a Docker container with significant security
              restrictions.
            </li>
            <li>
              {autoRun
                ? 'Generated code will run without asking you to approve each snippet.'
                : 'You will be shown each code snippet and asked to approve or deny it individually.'}
            </li>
          </ul>
        </div>

        <div>
          <p className="font-medium mb-2">What the sandboxed code CAN do:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              Run arbitrary JavaScript/Node.js code, including{' '}
              <code className="px-1 py-0.5 rounded-control bg-surface-2 font-mono text-xs">
                require(&apos;child_process&apos;)
              </code>
            </li>
            <li>
              Read the container&apos;s filesystem (standard Node.js image
              contents)
            </li>
            <li>
              Write to{' '}
              <code className="px-1 py-0.5 rounded-control bg-surface-2 font-mono text-xs">
                /tmp
              </code>{' '}
              (up to 64MB, non-persistent)
            </li>
            <li>Use up to 128MB of memory and 0.5 CPU for up to 30 seconds</li>
            <li>Spawn up to 32 processes inside the container</li>
          </ul>
        </div>

        <div>
          <p className="font-medium mb-2">What the sandboxed code CANNOT do:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Access the network (networking is fully disabled)</li>
            <li>Read or write your host filesystem (no volumes are mounted)</li>
            <li>
              Persist any data between executions (containers are destroyed
              after each run)
            </li>
            <li>Escalate privileges (all Linux capabilities are dropped)</li>
            <li>
              Modify the container&apos;s root filesystem (it is read-only)
            </li>
          </ul>
        </div>

        <div className="border border-warning bg-warning-soft rounded-control p-4">
          <p className="font-medium mb-2">Residual risks — read carefully:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>Container escapes are possible.</strong> Docker sandboxing
              relies on Linux kernel namespaces and cgroups. Kernel
              vulnerabilities have historically allowed container escapes.
            </li>
            <li>
              <strong>The code is generated by an AI.</strong> The AI may
              produce code that behaves unexpectedly.
            </li>
            <li>
              <strong>Docker socket access is powerful.</strong> If your
              deployment mounts the Docker socket, the code execution feature
              has indirect access to a root-equivalent API on the host.
            </li>
            <li>
              <strong>You are responsible for your infrastructure.</strong> This
              feature is designed for self-hosted deployments where the operator
              understands and accepts these tradeoffs.
            </li>
          </ul>
        </div>

        {error && (
          <p role="alert" className="text-danger text-sm">
            {error}
          </p>
        )}

        <p className="text-fg-muted text-xs italic">
          {autoRun
            ? 'If you do not understand these risks, cancel. Disabling auto-run later does not stop code already running.'
            : 'If you do not understand the risks described above, do not enable code execution. Click "Decline" to deny this and all future code execution requests.'}
        </p>
      </div>
    </Modal>
  );
}
